# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseOcSyntaxDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for BaseOcSyntaxDemo

  target 'BaseOcSyntaxDemoTests' do
    pod 'MJExtension', '3.0.13'
  end

end
